# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
x = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [6]:
v = np.arange(10,49)

4. Find the shape of previous array in question 3

In [7]:
v.shape

(39,)

5. Print the type of the previous array in question 3

In [8]:
print(type(v))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [9]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/CSPS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/CSPS/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/CSPS/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

7. Print the dimension of the array in question 3


In [10]:
v.ndim

1

8. Create a boolean array with all the True values

In [16]:
np.full(10,True,bool)


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [17]:
d2=[[1,2,3],[11,22,33]]
d2

[[1, 2, 3], [11, 22, 33]]

10. Create a three dimensional array



In [19]:
d3=[[[2,3,4,4],[1,3,5,8],[11,22,33,44]]]
d3

[[[2, 3, 4, 4], [1, 3, 5, 8], [11, 22, 33, 44]]]

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [21]:
vec=np.arange(1,11)
vec[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [22]:
vec=np.zeros(10)
vec[4]=1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [28]:
vect = np.array([1, 2, 3, 4, 5])
vect.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [29]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [30]:
def minn(x, y):
    """Get the minimum of two items"""
    if x <= y:
        return x
    else:
        return y

pair_min = np.vectorize(minn, otypes=[int])
vect1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
vect2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])

pair_min(vect1, vect2)

array([[0, 2, 1],
       [4, 2, 6]])

17. Extract all odd numbers from arr with values(0-9)

In [35]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [36]:
a[a%2!=0]=-1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [37]:
a[5:9]=12
print(a)

[-1  2 -1  4 -1 12 12 12 12]


20. Create a 2d array with 1 on the border and 0 inside

In [40]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [43]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
                 
arr2d
                 


array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [44]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [45]:
arr2d=np.arange(2*5).reshape(2,5)
arr2d[0,0:]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [49]:
arr2d=np.arange(2*5).reshape(2,5)
arr2d[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [51]:
arr2d=np.arange(2*5).reshape(2,5)
print(arr2d[0:2,2])

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [53]:
arr2d=np.random.uniform(0,100, size=(10,10))
print("Minimum value is " ,arr2d.min())
print("Maximum value is " ,arr2d.max())

Minimum value is  0.06848441200585365
Maximum value is  99.2978149774173


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [54]:
a = np.array([1,2,5,9,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4, 9])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [55]:
np.where(a==b)

(array([1, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [56]:
names = np.array(['Boby', 'Jose', 'Will', 'Bob', 'Will', 'Jose', 'Jose']) 
data = np.random.randn(7, 4)
data[names!="Will"]

array([[ 0.62640927,  1.0821574 , -0.29450876, -1.32701286],
       [ 1.80384585,  0.11574379,  0.84697331,  0.38769558],
       [ 0.62799127, -0.39345632, -0.54001324, -1.92457841],
       [ 1.23426853,  0.18055255,  0.61883509, -0.78499245],
       [ 0.75972487,  1.24713   ,  0.27323672, -0.25592948]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
a=data[names!="Will"]
b=data[names=="Joe"]
a
b


array([[-0.91462366, -1.91667246,  0.6330146 ,  1.10865943],
       [ 0.36824876, -0.20293238, -1.56578252, -0.72215469],
       [-0.33565713, -1.7027182 , -0.42117126, -0.40369504]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [60]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[13.46155686 10.56980227  5.15387216]
 [ 8.99839367  7.73377924  5.24208431]
 [ 9.16476151 11.17694544  4.89459264]
 [ 6.75778885  8.59531046  2.48593547]
 [ 1.49134325  1.89954425  6.10263887]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [61]:
rand_arr = np.random.uniform(1,16, size=(2,2,4))
rand_arr

array([[[14.49920221,  9.83660508,  9.91202291,  6.93914724],
        [11.1237018 ,  7.05631066,  3.37394338, 12.93226318]],

       [[14.31816392,  9.75128396, 13.95849369,  2.71752126],
        [ 7.93851071, 11.27899717,  1.57187687,  4.75393622]]])

33. Swap axes of the array you created in Question 32

In [62]:
np.swapaxes(rand_arr,0,2)

array([[[14.49920221, 14.31816392],
        [11.1237018 ,  7.93851071]],

       [[ 9.83660508,  9.75128396],
        [ 7.05631066, 11.27899717]],

       [[ 9.91202291, 13.95849369],
        [ 3.37394338,  1.57187687]],

       [[ 6.93914724,  2.71752126],
        [12.93226318,  4.75393622]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [63]:
arr=np.arange(4,15)
y = np.sqrt(np.abs(arr))
arr
y

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        , 3.16227766, 3.31662479, 3.46410162, 3.60555128,
       3.74165739])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [64]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5,8,5,3,8,2])
b = np.array([6, 3, 4, 8, 9, 7, 1,1,8,4,9,3])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5, 8, 8, 4, 9, 3])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [66]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [67]:

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])
sampleArray[1,0:]=newColumn[0:]
print(sampleArray)

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [68]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [69]:
rma = np.random.rand(5,4)
print(rma)
rma.sum()

[[0.86489293 0.84223694 0.16489869 0.75186186]
 [0.16278735 0.93858897 0.11118901 0.2878279 ]
 [0.17239122 0.54001608 0.82431438 0.34048492]
 [0.0994285  0.16239871 0.72971355 0.02106169]
 [0.6132349  0.72225475 0.9218057  0.80725633]]


10.078644347254931